# Netlify Configuration for Athlete-Time
# Main site at root, Community app at /community

[build]
  publish = "."
  command = "cd community-new && npm install && npm run build && cd .. && mkdir -p community && cp -r community-new/dist/* community/"

[build.environment]
  NODE_VERSION = "20"

# Community SPA routing - all /community/* routes go to community app
[[redirects]]
  from = "/community/*"
  to = "/community/index.html"
  status = 200

# Root site - other routes stay as static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production environment variables
[context.production.environment]
  VITE_API_URL = "https://athlete-time-backend.onrender.com"

# Development branch
[context.branch-deploy.environment]
  VITE_API_URL = "https://athlete-time-backend.onrender.com"
