services:
  # 커뮤니티 백엔드 서버 (HTTP)
  - type: web
    name: athlete-time-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    
  # 채팅 WebSocket 서버
  - type: web
    name: athlete-time-chat
    runtime: node
    buildCommand: npm install
    startCommand: npm run start:chat
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3006
    healthCheckPath: /api/health
    autoDeploy: true