services:
  # 커뮤니티 백엔드 서버 (PostgreSQL + Cloudinary + WebSocket)
  - type: web
    name: athlete-time-backend
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
      - key: DATABASE_URL
        fromDatabase:
          name: athlete-time-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://athlete-time.netlify.app
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: athlete-time-db
    plan: starter
    region: oregon
    databaseName: athlete_time
    user: athlete_time