# Netlify Configuration for Athlete-Time Community
# https://athlete-time.netlify.app

[build]
  base = "community-new"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production environment variables
[context.production.environment]
  VITE_API_URL = "https://athlete-time-backend.onrender.com"

# Development branch
[context.branch-deploy.environment]
  VITE_API_URL = "https://athlete-time-backend.onrender.com"
