import type { BoardSummary, CommentThread, PostDetail, PostSummary } from '../../lib/types'

const now = new Date()
const iso = (daysAgo: number) => new Date(now.getTime() - daysAgo * 24 * 60 * 60 * 1000).toISOString()

export const mockBoards: BoardSummary[] = [
  {
    id: 'general',
    name: '자유 게시판',
    slug: 'general',
    description: '러닝 이야기, 잡담, 일상 공유',
    icon: '💬',
    order: 1,
    isActive: true,
    createdAt: iso(180),
    todayPostCount: 34,
    todayCommentCount: 212,
  },
  {
    id: 'qa',
    name: '질문 & 답변',
    slug: 'qa',
    description: '훈련/장비/부상 관련 질문과 답변',
    icon: '❓',
    order: 2,
    isActive: true,
    createdAt: iso(200),
    todayPostCount: 18,
    todayCommentCount: 97,
  },
  {
    id: 'competition',
    name: '대회 소식',
    slug: 'competition',
    description: '국내외 대회 정보와 참가 후기',
    icon: '🏁',
    order: 3,
    isActive: true,
    createdAt: iso(320),
    todayPostCount: 9,
    todayCommentCount: 54,
  },
  {
    id: 'training',
    name: '훈련 노트',
    slug: 'training',
    description: '훈련 일지, 프로그램 공유',
    icon: '📓',
    order: 4,
    isActive: true,
    createdAt: iso(90),
    todayPostCount: 27,
    todayCommentCount: 133,
  },
  {
    id: 'market',
    name: '중고 거래',
    slug: 'market',
    description: '러닝화, 기어, 웨어 등 거래',
    icon: '🛒',
    order: 5,
    isActive: true,
    createdAt: iso(40),
    todayPostCount: 11,
    todayCommentCount: 44,
  },
]

export const mockPosts: PostSummary[] = [
  {
    id: 'p1',
    boardId: 'general',
    boardSlug: 'general',
    boardName: '자유 게시판',
    title: '마라톤 시즌 대비 4주 훈련 계획 공유합니다',
    excerpt: '10월 풀코스 대비해서 제가 사용 중인 4주 마무리 프로그램 공유합니다. 주당 5회, 키 포인트는 LT 조절...',
    authorNick: '서브330가즈아',
    createdAt: iso(0.3),
    updatedAt: iso(0.3),
    views: 1423,
    likeCount: 187,
    dislikeCount: 3,
    commentCount: 58,
    tags: ['훈련', '마라톤', '계획표'],
    isNotice: false,
    isHot: true,
    hasPoll: false,
    thumbnailUrl: 'https://images.unsplash.com/photo-1526401281623-359c08ad81fd?auto=format&fit=crop&w=400&q=60',
  },
  {
    id: 'p2',
    boardId: 'general',
    boardSlug: 'general',
    boardName: '자유 게시판',
    title: '📢 커뮤니티 베타 오픈 안내',
    excerpt: 'AthleteTime 커뮤니티가 드디어 베타로 오픈했습니다. 로그인 없이 자유롭게 이용 가능하며, 회원 기능은 준비 중입니다.',
    authorNick: '운영팀',
    createdAt: iso(2),
    updatedAt: iso(1.8),
    views: 982,
    likeCount: 76,
    dislikeCount: 0,
    commentCount: 12,
    tags: ['공지'],
    isNotice: true,
    isHot: false,
    hasPoll: false,
  },
  {
    id: 'p3',
    boardId: 'qa',
    boardSlug: 'qa',
    boardName: '질문 & 답변',
    title: '서브4 목표인데 주간 LSD 페이스 얼마가 적당할까요?',
    excerpt: '3시간 58분 목표로 훈련 중인데 LSD를 어느 정도 페이스로 가야할지 궁금합니다. 현재 10km PB는 47분입니다.',
    authorNick: '초보러너123',
    createdAt: iso(0.6),
    updatedAt: iso(0.6),
    views: 622,
    likeCount: 45,
    dislikeCount: 1,
    commentCount: 27,
    tags: ['훈련', 'LSD'],
    isNotice: false,
    isHot: true,
    hasPoll: false,
  },
  {
    id: 'p4',
    boardId: 'competition',
    boardSlug: 'competition',
    boardName: '대회 소식',
    title: '서울마라톤 2025 참가 접수 일정 나왔네요',
    excerpt: '서울마라톤 공식 홈페이지에 2025 대회 일정이 올라왔습니다. 사전 등록 일정과 참가비 안내 공유합니다.',
    authorNick: 'RunningCat',
    createdAt: iso(1.2),
    updatedAt: iso(1.1),
    views: 834,
    likeCount: 63,
    dislikeCount: 0,
    commentCount: 19,
    tags: ['대회', '공지'],
    isNotice: false,
    isHot: false,
    hasPoll: false,
  },
  {
    id: 'p5',
    boardId: 'training',
    boardSlug: 'training',
    boardName: '훈련 노트',
    title: '400m 인터벌 10세트 후기 (사진 있음)',
    excerpt: '오늘은 트랙에서 400m 인터벌을 10세트 진행했습니다. 페이스와 심박 기록 공유드려요. 사진 참고!',
    authorNick: 'TrackLover',
    createdAt: iso(0.4),
    updatedAt: iso(0.4),
    views: 512,
    likeCount: 71,
    dislikeCount: 2,
    commentCount: 33,
    tags: ['인터벌', '훈련일지'],
    isNotice: false,
    isHot: true,
    hasPoll: false,
    thumbnailUrl: 'https://images.unsplash.com/photo-1526401485004-46910ecc8e51?auto=format&fit=crop&w=400&q=60',
  },
]

const mockComments: CommentThread[] = [
  {
    id: 'c1',
    postId: 'p1',
    parentId: null,
    authorNick: '런딸기',
    authorBadge: '7년차 러너',
    content: '마지막 주에 템포런을 조금 줄이고 회복런 위주로 가는 것을 추천드려요!',
    createdAt: iso(0.25),
    likeCount: 42,
    dislikeCount: 0,
    reportCount: 0,
    children: [
      {
        id: 'c1-1',
        postId: 'p1',
        parentId: 'c1',
        authorNick: '서브330가즈아',
        content: '와 조언 감사합니다! 말씀대로 해볼게요.',
        createdAt: iso(0.24),
        likeCount: 12,
        dislikeCount: 0,
        reportCount: 0,
        children: [],
      },
    ],
  },
  {
    id: 'c2',
    postId: 'p1',
    parentId: null,
    authorNick: 'Sub3Runner',
    content: '롱런 이후 근력운동 루틴도 같이 공유해주시면 좋겠어요!',
    createdAt: iso(0.23),
    likeCount: 9,
    dislikeCount: 0,
    reportCount: 0,
    children: [],
  },
]

export const mockPostDetail: PostDetail = {
  ...mockPosts[0],
  content:
    '## 4주 마무리 프로그램\n\n- 월: 완전 휴식\n- 화: LT 템포런 8km (페이스 4:30)\n- 수: 가벼운 조깅 8km + 코어\n- 목: 인터벌 6 x 1km (페이스 4:05)\n- 금: 휴식 또는 크로스 트레이닝\n- 토: 롱런 28km (페이스 4:55)\n- 일: 조깅 10km 회복\n\n> *베타 기간에는 PDF 업로드가 제한됩니다. 추후 파일 업로드 기능을 열 예정입니다.*',
  attachments: [
    {
      id: 'a1',
      fileName: '4week-plan.png',
      fileSize: 245_000,
      fileUrl: 'https://images.unsplash.com/photo-1526401485004-46910ecc8e51?auto=format&fit=crop&w=800&q=60',
      thumbnailUrl: 'https://images.unsplash.com/photo-1526401485004-46910ecc8e51?auto=format&fit=crop&w=400&q=60',
      mimeType: 'image/png',
    },
  ],
  comments: mockComments,
  reportCount: 0,
}

export const mockPopularPosts: PostSummary[] = mockPosts
  .filter((post) => post.isHot)
  .slice(0, 5)
  .map((post, index) => ({
    ...post,
    likeCount: post.likeCount + index * 2,
    views: post.views + index * 120,
  }))
